SCRIPT_START gUnk_0800AB08
StartScript 
_0807E864 
Call 0x0807df29
SetEntityPositionRelative 0x01480088
Call 0x0807f845
_0807E8E4_3 
CallWithArg
.short 0xf6e9
.short 0x0807
.short 0x0008
.short 0x0000
@ End of 4 parameters
CallWithArg
.short 0xf75d
.short 0x0807
.short 0x0088
.short 0x00a8
@ End of 4 parameters
SoundReq 0x00f7
StopScript 
Wait 0x0078
_0807F0B4 0x0001
SetEntityPositionRelative 0x00780088
Call 0x0807f5c1
TextboxNoOverlapFollowPos
.short 0x1664
.short 0x0000
@ End of 2 parameters
_0807EA94 
TextboxNoOverlapFollowPos
.short 0x165e
.short 0x000e
@ End of 2 parameters
_0807EA94 
CallWithArg
.short 0xdded
.short 0x0805
.short 0x0001
.short 0x0000
@ End of 4 parameters
_0807F0C8 0xffff, 0x0000
