#ifndef PLAYERITEM_H
#define PLAYERITEM_H

typedef enum {
    PLAYER_ITEM_NONE,
    PLAYER_ITEM_SWORD,
    PLAYER_ITEM_BOMB,
    PLAYER_ITEM_BOOMERANG,
    PLAYER_ITEM_BOW,
    PLAYER_ITEM_SHIELD,
    PLAYER_ITEM_LANTERN,
    PLAYER_ITEM_NULLED,
    PLAYER_ITEM_GUST_JAR,
    PLAYER_ITEM_PACCI_CANE,
    PLAYER_ITEM_NONE2, // Mole Mitts
    PLAYER_ITEM_NONE3, // Rocs Cape
    PLAYER_ITEM_DASH_SWORD,
    PLAYER_ITEM_CELL_OVERWRITE_SET,
    PLAYER_ITEM_BOTTLE,
    PLAYER_ITEM_SWORD_BEAM1,
    PLAYER_ITEM_GUST,
    PLAYER_ITEM_GUST_BIG,
    PLAYER_ITEM_PACCI_CANE_PROJECTILE,
    PLAYER_ITEM_HELD_OBJECT,
    PLAYER_ITEM_SPIRAL_BEAM,
    PLAYER_ITEM_FIRE_ROD_PROJECTILE,
    PLAYER_ITEM_SWORD_BEAM2,
    PLAYER_ITEM_NULLED2,
    PLAYER_ITEM_CELL_OVERWRITE_SET2,
} PlayerItem;

#endif // PLAYERITEM_H
