#ifndef PLAYERITEM_H
#define PLAYERITEM_H

typedef enum {
    PLAYER_ITEM_NONE,
    PLAYER_ITEM_SWORD,
    PLAYER_ITEM_BOMB,
    PLAYER_ITEM_3,
    PLAYER_ITEM_BOW,
    PLAYER_ITEM_SHIELD,
    PLAYER_ITEM_LANTERN,
    PLAYER_ITEM_7,
    PLAYER_ITEM_GUST_JAR,
    PLAYER_ITEM_PACCI_CANE,
    PLAYER_ITEM_A,
    PLAYER_ITEM_B,
    PLAYER_ITEM_C,
    PLAYER_ITEM_CELL_OVERWRITE_SET,
    PLAYER_ITEM_BOTTLE,
    PLAYER_ITEM_SWORD_BEAM1,
    PLAYER_ITEM_10,
    PLAYER_ITEM_11,
    PLAYER_ITEM_12,
    PLAYER_ITEM_13,
    PLAYER_ITEM_14,
    PLAYER_ITEM_15,
    PLAYER_ITEM_SWORD_BEAM2,
    PLAYER_ITEM_17,
    PLAYER_ITEM_CELL_OVERWRITE_SET2,
} PlayerItem;

#endif
