#ifndef SCRIPT_MACROS_H
#define SCRIPT_MACROS_H

// Generated by disassemble_script.py
#define START_SCRIPT(name) const unsigned short name[] = {
#define END_SCRIPT() };
#define WORD_TO_SHORTS(word) (unsigned short)(word & 0xffff),(unsigned short)(word >> 16)

#define nullsub_507() 0x0400, 
#define sub_0807E004() 0x0401, 
#define sub_0807E014() 0x0402, 
#define sub_0807E024(s) 0x0803, s,
#define sub_0807E050(s) 0x0804, s,
#define sub_0807E064(s) 0x0805, s,
#define sub_0807E078(s) 0x0806, s,
#define sub_0807E0A0(w) 0x0c07, WORD_TO_SHORTS(w),
#define sub_0807E0B8(w) 0x0c08, WORD_TO_SHORTS(w),
#define sub_0807E0CC(w) 0x0c09, WORD_TO_SHORTS(w),
#define sub_0807E0E0(w) 0x0c0a, WORD_TO_SHORTS(w),
#define sub_0807E10C(w) 0x0c0b, WORD_TO_SHORTS(w),
#define sub_0807E124(a,b) 0x140c, WORD_TO_SHORTS(a), WORD_TO_SHORTS(b),
#define sub_0807E148(w) 0x0c0d, WORD_TO_SHORTS(w),
#define sub_0807E158(w) 0x0c0e, WORD_TO_SHORTS(w),
#define sub_0807E188(s) 0x080f, s,
#define sub_0807E1D8(s) 0x0810, s,
#define sub_0807E4AC(s) 0x0811, s,
#define sub_0807E260(s) 0x0815, s,
#define sub_0807E2A8(s) 0x0817, s,
#define sub_0807E2E4() 0x0418, 
#define sub_0807E5F8(w) 0x0c28, WORD_TO_SHORTS(w),
#define sub_0807E680(s) 0x0831, s,
#define sub_0807E6AC(w) 0x0c33, WORD_TO_SHORTS(w),
#define sub_0807E864() 0x0443, 
#define sub_0807E878() 0x0444, 
#define sub_0807E8C4(w) 0x0c47, WORD_TO_SHORTS(w),
#define sub_0807E8E4() 0x0449, 
#define sub_0807E8E4a() 0x044a, 
#define sub_0807E8E4b() 0x044b, 
#define sub_0807E8E4c() 0x044c, 
#define sub_0807E930(s) 0x0850, s,
#define sub_0807E9D4() 0x0453, 
#define sub_0807E9DC() 0x0454, 
#define sub_0807EA94() 0x0459, 
#define sub_0807EAD0(a,b) 0x0c5c, a,b,
#define sub_0807EB28(s) 0x085f, s,
#define sub_0807EB8C() 0x0464, 
#define sub_0807EBC0(s) 0x0867, s,
#define sub_0807EC1C(s) 0x086d, s,
#define sub_0807EE30() 0x0475, 
#define sub_0807EF80(s) 0x0879, s,
#define sub_0807EFAC(s) 0x087c, s,
#define sub_0807EFE4() 0x047e, 

#endif
