#ifndef SCRIPT_MACROS_H
#define SCRIPT_MACROS_H
// Generated by disassemble_script.py
#define START_SCRIPT(name) asm(".globl "#name); asm(".section .rodata"); asm(#name":");
#define END_SCRIPT() asm(".short 0xffff");

#define nullsub_507() asm(".short 0x0400");
#define sub_0807E004() asm(".short 0x0401");
#define sub_0807E014() asm(".short 0x0402");
#define sub_0807E024(s) asm(".short 0x0803");asm(".short " #s);
#define sub_0807E050(s) asm(".short 0x0804");asm(".short " #s);
#define sub_0807E064(s) asm(".short 0x0805");asm(".short " #s);
#define sub_0807E078(s) asm(".short 0x0806");asm(".short " #s);
#define sub_0807E0A0(w) asm(".short 0x0c07");asm(".word " #w);
#define sub_0807E0B8(w) asm(".short 0x0c08");asm(".word " #w);
#define sub_0807E0CC(w) asm(".short 0x0c09");asm(".word " #w);
#define sub_0807E0E0(w) asm(".short 0x0c0a");asm(".word " #w);
#define sub_0807E10C(w) asm(".short 0x0c0b");asm(".word " #w);
#define sub_0807E124(a,b) asm(".short 0x140c");asm(".word " #a);asm(".word " #b);
#define sub_0807E148(w) asm(".short 0x0c0d");asm(".word " #w);
#define sub_0807E158(w) asm(".short 0x0c0e");asm(".word " #w);
#define sub_0807E188(s) asm(".short 0x080f");asm(".short " #s);
#define sub_0807E1D8(s) asm(".short 0x0810");asm(".short " #s);
#define sub_0807E4AC(s) asm(".short 0x0811");asm(".short " #s);
#define sub_0807E260(s) asm(".short 0x0815");asm(".short " #s);
#define sub_0807E2A8(s) asm(".short 0x0817");asm(".short " #s);
#define sub_0807E2E4() asm(".short 0x0418");
#define sub_0807E5F8(w) asm(".short 0x0c28");asm(".word " #w);
#define sub_0807E680(s) asm(".short 0x0831");asm(".short " #s);
#define sub_0807E6AC(w) asm(".short 0x0c33");asm(".word " #w);
#define sub_0807E864() asm(".short 0x0443");
#define sub_0807E878() asm(".short 0x0444");
#define sub_0807E8C4(w) asm(".short 0x0c47");asm(".word " #w);
#define sub_0807E8E4_0() asm(".short 0x0449");
#define sub_0807E8E4_1() asm(".short 0x044a");
#define sub_0807E8E4_2() asm(".short 0x044b");
#define sub_0807E8E4_3() asm(".short 0x044c");
#define sub_0807E930(s) asm(".short 0x0850");asm(".short " #s);
#define sub_0807E9D4() asm(".short 0x0453");
#define sub_0807E9DC() asm(".short 0x0454");
#define sub_0807EA94() asm(".short 0x0459");
#define sub_0807EAD0(a,b) asm(".short 0x0c5c");asm(".short " #a);asm(".short " #b);
#define sub_0807EB28(s) asm(".short 0x085f");asm(".short " #s);
#define sub_0807EB8C() asm(".short 0x0464");
#define sub_0807EBC0(s) asm(".short 0x0867");asm(".short " #s);
#define sub_0807EC1C(s) asm(".short 0x086d");asm(".short " #s);
#define sub_0807EE30() asm(".short 0x0475");
#define sub_0807EF80(s) asm(".short 0x0879");asm(".short " #s);
#define sub_0807EFAC(s) asm(".short 0x087c");asm(".short " #s);
#define sub_0807EFE4() asm(".short 0x047e");
#endif