#ifndef TILES_H
#define TILES_H

typedef enum {
    TILE_ACT_CUT = 0x0,
    TILE_ACT_ROCKBREAKER = 0x1,
    TILE_ACT_BOOMERANG = 0x2,
    TILE_ACT_BOMB = 0x3,
    TILE_ACT_ARROW = 0x4,
    TILE_ACT_GUST = 0x5,
    TILE_ACT_LIFT = 0x6,
    TILE_ACT_FIRE = 0x7,
    TILE_ACT_PLAYER_WALK = 0x8,
    TILE_ACT_ENEMY_WALK = 0x9,
    TILE_ACT_PACCI = 0xA,
    TILE_ACT_SWORDBEAM = 0xC,
    TILE_ACT_DIG = 0xD,
    TILE_ACT_MINIGUST = 0xE,
} TileInteraction;

typedef enum {
    CUT_BUSH = 0x1C,
    CUT_GRASS = 0x1D,
    CUT_SIGNPOST = 0x1E,
    CUT_TREE = 0x1F,
    ROCK = 0x55,
    CHEST = 0x73,
    CHEST_OPEN = 0x74,
    TORCH = 0x76,
    TORCH_LIT = 0x77,
    PRESSURE_BUTTON = 0x78,
    PRESSURE_BUTTON_PRESSED = 0x79,
    PRESSURE_SQUARE = 0x7a,
    PRESSURE_SQUARE_PRESSED = 0x7b,
    STAIRS_UP = 0x92,
    STAIRS_DOWN = 0x93,
    SIGNPOST = 0x176,
    PERMA_ROCK = 0x1D3,
    PERMA_ROCK2 = 0x1D4,
    PERMA_ROCK3 = 0x1D5,
    PERMA_ROCK4 = 0x1D6,
} Tile;

#endif // TILES_H
