#ifndef SAVEFILE_WINDCREST_H
#define SAVEFILE_WINDCREST_H

typedef enum WindcrestID {
    WINDCREST_MT_CRENEL = 24,
    WINDCREST_VEIL_FALLS,
    WINDCREST_CLOUD_TOPS,
    WINDCREST_HYRULE_TOWN,
    WINDCREST_LAKE_HYLIA,
    WINDCREST_CASTOR_WILDS,
    WINDCREST_SOUTH_HYRULE_FIELD,
    WINDCREST_MINISH_WOODS,
} WindcrestID;

#endif // SAVEFILE_WINDCREST_H
